spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'

  data:
    redis:
      host: localhost
      password: '${custom.redis.password}'
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false